### ISSUE TITLE
Crossref bug

### ISSUE THREAD

**Issue by pekrau** [pekrau/Publications#279]
When parsing 10.1007/978-3-540-76782-4_4

Traceback (most recent call last):
  File "/opt/rh/rh-python36/root/usr/lib64/python3.6/site-packages/tornado/web.py", line 1701, in _execute
    result = method(*self.path_args, **self.path_kwargs)
  File "/opt/rh/rh-python36/root/usr/lib64/python3.6/site-packages/tornado/web.py", line 3178, in wrapper
    return method(self, *args, **kwargs)
  File "/var/www/apps/publ/affiliated/Publications/publications/publication.py", line 695, in post
    clean=not self.is_admin())
  File "/var/www/apps/publ/affiliated/Publications/publications/publication.py", line 287, in fetch
    new = crossref.fetch(identifier)
  File "/var/www/apps/publ/affiliated/Publications/publications/crossref.py", line 25, in fetch
    return parse(response.json())
  File "/var/www/apps/publ/affiliated/Publications/publications/crossref.py", line 36, in parse
    result['published']  = get_published(data)
  File "/var/www/apps/publ/affiliated/Publications/publications/crossref.py", line 113, in get_published
    parts = [int(i) for i in item['date-parts'][0]]
  File "/var/www/apps/publ/affiliated/Publications/publications/crossref.py", line 113, in <listcomp>
    parts = [int(i) for i in item['date-parts'][0]]
TypeError: int() argument must be a string, a bytes-like object or a number, not 'NoneType'

**Comment by pekrau** [comment]
Probably fixed, but needs to be checked.

**Comment by pekrau** [comment]
See #286.
