### ISSUE TITLE
Preferred platform?

### ISSUE THREAD

**Issue by p1ersson** [pekrau/Publications#385]
Tried installing this on a Ubuntu 20. some issues and small hickups made me wonder, best platfor for this to run on?

**Comment by pekrau** [comment]
I run it locally on Ubuntu 20, and in production on SELinux (forget which version).

Linux is the preferred platform, I know that Windows is awful.

Since you do not give any specifics, it's hard for me to say anything more concrete.

**Comment by p1ersson** [comment]
Wasnt sure if I used the right plattform (i test on a clean Ubuntu 20 VM), but then I knows its SBS - its my lack of pythonskill.
I add some meat then:
When I run the create database-script -  fail:

root@tspubref:/usr/src/Publications/publications# pwd
/usr/src/Publications/publications
root@tspubref:/usr/src/Publications/publications# ls
account.py           crossref.py  __init__.py  logs.py            researcher.py  settings_template.yaml  undump.py
api                  designs.py   journal.py   publication.py     saver.py       static                  utils.py
app_publications.py  dump.py      label.py     pubmed.py          scripts        templates
constants.py         home.py      login.py     requesthandler.py  search.py      uimodules.py
root@tspubref:/usr/src/Publications/publications# python3 scripts/init_database.py
Traceback (most recent call last):
  File "scripts/init_database.py", line 13, in <module>
    path_root = Path(__file__).parents[2]
  File "/usr/lib/python3.8/pathlib.py", line 621, in __getitem__
    raise IndexError(idx)
IndexError: 2

Thank you in advance for any help

**Comment by pekrau** [comment]
This operation works for me. Have you configured your `/usr/src/Publications/site/settings.yaml` file?

**Comment by p1ersson** [comment]
I have, DATABASE_NAME etc matches the setup in couchdb (i did that via webgui)
http-parts is set  to localhost, would that cause an issue here?

**Comment by p1ersson** [comment]
I don't know what I'm talking about in python... But - pathlib sounds some like other error. (pathlib is included in python 3 as default as I understad, i tried pip install, no change in database-script function.
I havent installed python3 is python so I dont have a "python" only link. The machine is a pretty clean Ubuntu 20 server, packages installed per instructions and dependencies.


Traceback (most recent call last):
  File "scripts/init_database.py", line 13, in <module>
    path_root = Path(__file__).parents[2]
  File "/usr/lib/python3.8/pathlib.py", line 621, in __getitem__
    raise IndexError(idx)

**Comment by pekrau** [comment]
I do not understand this traceback. The line 13 in `scripts/init_database.py` contains nothing obvious to trigger this error.

But I still think this is a setup problem. Could you post your `settings.yaml`, excluding the password fields?

While you are at it, go to `/usr/src/Publications/publications`, start the Python interpreter and execute:

```
$ python3
>>> import sys
>>> print(sys.path)
```

**Comment by p1ersson** [comment]
`root@tspubref:/usr/src/Publications/publications# python3
Python 3.8.10 (default, Jun  2 2021, 10:49:15) 
[GCC 9.4.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import sys
>>> print(sys.path)
['', '/usr/lib/python38.zip', '/usr/lib/python3.8', '/usr/lib/python3.8/lib-dynload', '/usr/local/lib/python3.8/dist-packages', '/usr/lib/python3/dist-packages']
>>> `


 
[settings_template.yaml.txt](https://github.com/pekrau/Publications/files/7210068/settings_template.yaml.txt)

**Comment by pekrau** [comment]
Your Python path is lacking the top directory of the Publications package. One way of setting it is to set the environment variable PYTHONPATH, in bash like so, before executing any Python code:
```
$ export PYTHONPATH=/usr/src/Publications
```
This needs to be done in e.g. `.bashrc` so that the setting is there when you need to restart the server.

What you posted was the template settings file, not the actual settings file your setup will be using. You do have a settings file `/usr/src/Publications/settings.yaml`? Copy the template settings file to there, and edit it.

**Comment by p1ersson** [comment]
> Your Python path is...

Hm did the that, same error  (isnt current working dir included per default?)

> What you posted was the template settings file, not the actual settings file your setup will be using. You do have a settings file /usr/src/Publications/settings.yaml? Copy the template settings file to there, and edit it.

*facepalm*
